apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  glusterfs:
    path: replica1
    endpoints: test-pv-ep
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: Endpoints
apiVersion: v1
metadata:
  name: test-pv-ep
subsets:
- addresses:
  - ip: 192.168.16.82
  ports:
  - port: 1
- addresses:
  - ip: 192.168.16.114
  ports:
  - port: 1
- addresses:
  - ip: 192.168.16.145
  ports:
  - port: 1
- addresses:
  - ip: 192.168.16.146
  ports:
  - port: 1
