apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    addon-manager.caicloud.io/key: kubernetes-mongo-pv
    addon-manager.caicloud.io/name: kubernetes-admin
    addon-manager.caicloud.io/version: v0.0.2
    caicloud-app: kubernetes-admin-mongo-data
    caicloud.io/cluster-service: "true"
  name: kubernetes-admin-mongo-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  glusterfs:
    endpoints: glusterfs-cluster
    path: infra-kubernetes-admin-mongo-beta