---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: console-web-test-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  glusterfs:
    endpoints: glusterfs-cluster
    path: tmp