apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: failed-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: sbsb
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi