apiVersion: v1
kind: Pod
metadata:
  name: glusterfs-tester
spec:
  containers:
  - name: glusterfs
    image: cargo.caicloud.io/caicloud/debian:jessie
    volumeMounts:
    - mountPath: "/mnt/glusterfs"
      name: replicavol
    args:
    - tail
    - "-f"
    - "/dev/null"
  volumes:
  - name: replicavol
    glusterfs:
      endpoints: test-pv-ep
      path: replica1

      