apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heketi-bigdata
  labels:
    caicloud-app-name: heketi-bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      caicloud-app-name: heketi-bigdata
  template:
    metadata:
      labels:
        caicloud-app-name: heketi-bigdata
    spec:
      containers:
      - image: cargo.caicloudprivatetest.com/caicloud/heketi:auto-topology
        imagePullPolicy: Always
        name: heketi
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/heketi
          name: heketi-volume
        - mountPath: /root/.ssh
          name: ssh-secret
      volumes:
      - name: ssh-secret
        secret:
          defaultMode: 420
          secretName: ssh-pao-secret
      - glusterfs:
          endpoints: glusterfs-cluster
          path: heketi-bigdata
        name: heketi-volume