apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heketi-pv
  labels:
    app: heketi-pv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heketi-pv
    spec:
      containers:
      - name: heketi
        image: cargo.caicloud.io/caicloud/heketi:with-cli
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/heketi
          name: heketi-volume
      volumes:
      - name: heketi-volume
        glusterfs:
          endpoints: glusterfs-cluster
          path: heketi-storage