apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heketi
  labels:
    app: heketi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heketi
    spec:
      containers:
      - name: heketi
        image: cargo.caicloudprivatetest.com/caicloud/heketi:auto_topology
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/heketi
          name: heketi-volume
        - mountPath: /root/.ssh
          name: ssh-secret
          readOnly: true
        env:
        - name: CLUSTERS
          value: 192.168.16.229,192.168.16.230,192.168.16.231
        - name: PARTITION
          value: /dev/vdb
      volumes:
      - name: ssh-secret
        secret:
          secretName: ssh-key-secret 
      - name: heketi-volume
        glusterfs:
          endpoints: glusterfs-cluster
          path: rhel-heketi-vol
