apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-ep
spec:
 accessModes:
  - ReadWriteMany
 resources:
   source:
    endpionts: glusterfs-dynamic-gluster-test
   requests:
     storage: 1Gi